import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from './style.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sanzo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sanzo
        </h1>

        <p className="description">
          Sanzo is a demo for customized resource retrieval based on&nbsp;
          <a
            target="_blank"
            rel="noreferrer"
            href="https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API"
          >
            Service Worker
          </a>.
        </p>

        <ul className={styles.grid}>
          <li className={styles.card}>
            <h2>Image</h2>
            <img
              alt="Fabric"
              src="https://statics-file.qiniu.io/sanzo/samples/fabric.jpg"
            />
          </li>

          {/* <li className={styles.card}>
            <h2>Video</h2>
            <video controls src="https://statics-file.qiniu.io/sanzo/samples/window.mp4"></video>
          </li>

          <li className={styles.card}>
            <h2>Audio</h2>
            <audio controls src="https://statics-file.qiniu.io/sanzo/samples/ukulele.mp3"></audio>
          </li> */}

        </ul>
      </main>
    </div>
  )
}

export default Home
